name: loantrack
description: Gestor de préstamos y pagos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0

  # Estado
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

  # Navegación
  go_router: ^17.2.2

  # Formularios
  flutter_form_builder: ^10.3.0+2
  form_builder_validators: ^11.3.0

  # Storage local
  shared_preferences: ^2.2.3

  # Fechas
  intl: ^0.20.0

  # PDF
  pdf: ^3.10.8
  printing: ^5.12.0

  # Utils
  equatable: ^2.0.5
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^4.0.0+1
  custom_lint: ^0.8.1
  riverpod_lint: ^3.1.0

flutter:
  uses-material-design: true